softeerbootcamp-6th/Team1-ImSnacks

.github/workflows/auto-issue-column-transition.yml
- close #71
---
- `PR 생성` 또는 `존재하는 PR이 draft에서 ready for review 상태로 이동하는 경우` 에 PR에 연결된 이슈가 프로젝트에서 **Under Review** status로 이동하는 자동화를 구현했습니다.
- 디폴트 워크플로우는 리뷰어가  **“Changes requested” 상태로 리뷰를 남겼을 때** **Under Review** status로 이동하기 때문에 적절하지 않다고 생각했습니다. [워크플로우 참고](https://github.com/orgs/softeerbootcamp-6th/projects/15/workflows/53388735)
- 테스트 완료했습니다. 
---
프로젝트에 PR 자체를 추가하는 방법도 있는데요! 현재는 그냥 이슈를 옮기는 방식으로 구현을 했습니다. 이렇게 진행하는 것이 괜찮으신지 의견 부탁드립니다 ~ 
---
=> [Feat] PR 생성 시 status 변경 자동화

.github/workflows/backend-ci.yml, backend/build.gradle
- close #68 
---
1. 테스트 커버리지 체크를 위한 jacoco 라이브러리 의존성을 추가했습니다.
- `./gradlew test` 또는 `./gradlew jacocoTestReport` 커맨드를 실행하면 `build/jacoco/index.html` 로 결과 파일이 생성됩니다.
- 브랜치 커버리지를 최소 80% 달성하는 것으로 룰을 세팅했습니다. (➡️ 현재는 코드에 브랜치가 없기 때문에 통과함)
- 💡 현재는 모든 클래스를  커버리지 체크 대상으로 뒀습니다. 추후에 엔티티 클래스 등 커버리지 체크 대상을 특정해야 합니다. 
2. CI 워크플로우에 커버리지 결과를 PR 코멘트로 남기는 스텝을 추가했습니다.
- 개발 초반에는 아래와 같이 최소 커버리지 조건을 20으로 작게 설정하고 조건 실패에도 continue 하도록 세팅했습니다.
- 본격적인 비즈니스 로직 구현에 들어가면 커버리지 조건을 강화할 예정입니다.
```
min-coverage-overall: 20
min-coverage-changed-files: 20
update-comment: true
continue-on-error: true
```
- PR 이 업데이트되면 새로운 커버리지 결과 코멘트가 달리는 것이 아니라 기존 코멘트가 업데이트 됩니다. 
---
없습니다.
---
* …
=> [Feat] 테스트 커버리지 체크를 위한 jacoco 라이브러리 적용

batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/WeatherWriter.java
- close #78
---
`ItemWriter` 구현에서 Chunk 내의 `ShortTermWeatherDto` 아이템들의 nx, ny를 모두 통일해버린 오류를 수정했습니다.
---
x
---
=> [Fix] WeatherRisk 불필요한 setter 삭제

batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/utils/params/WeatherJobParams.java, batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/ApiCallerTest.java, batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/ForecastTimeUtilsTest.java, batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/WeatherJobParamsTest.java
- close #99 
---
`public static JobParameters WeatherJobParams::get()`
- 기상청 api 호출 시에 필요한 시간 값을 JobParameters 형태로 반환합니다.
- `base_date`: 현재 날짜 (yyyyMMdd) / type: String
- `base_time`: 단기예보 API 예보 시각 중 현재 시각을 지나지 않은 가장 가까운 시각 (HH00) / type: String
---
---
---
=>  [Feat] Batch 서버 현재 시간으로 JobParameters 생성

backend/build.gradle, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/annotation/PreAuthorize.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/argumentResolver/JwtAuthHandlerArgumentResolver.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/exception/AuthResponseStatus.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/exception/JwtException.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/interceptor/JwtAuthInterceptor.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/jwt/AuthTokens.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/jwt/JwtProvider.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java, backend/src/main/resources/application.yml, backend/src/test/java/com/imsnacks/Nyeoreumnagi/NyeoreumnagiApplicationTests.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/authTest/JwtAuthHandlerArgumentResolverTest.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/authTest/JwtAuthInterceptorTest.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/authTest/JwtProviderTest.java
- close #113 
---
1. Jwt 생성/파싱을 위한 JwtProvider 클래스 생성
2. Controller 진입 전 request를 검증하는 interceptor 클래스 구현
3. interceptor에서 가져온 멤버 id를 controller 에서 받기 위한 argument resolver 구현 (커스텀 어노테이션 적용)
4. 각 클래스 테스트 코드 작성
5. 커스텀 예외 반환
---
리팩토링 할 부분 및 논리적 오류 검증 부탁드립니다. 
---
=> [Feat] 사용자 인증/인가를 위한 JWT 토큰 관련 기능 및 interceptor 구현

.github/workflows/CD.yml, backend/.deploy/Dockerfile, backend/build.gradle, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/GlobalExceptionHandler.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/SwaggerConfig.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Member.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/controller/MyWorkController.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/DeleteMyWorkRequest.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ResisterMyWorkRequest.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/WorkResponseStatus.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java, backend/src/main/resources/application.yml
- close #89
---
1. 농작업 삭제 기능을 구현했습니다. 
2. `Member` 엔티티의 id 타입을 원시타입에서 Wrapper 클래스로 변경했습니다. (Hibernate 권고사항)
3. Swagger 페이지에서 memberId 파라미터를 숨김 처리했습니다.
➡️ `Cookie` 헤더에서 jwt 를 가져와서 처리하여, 사용자가 직접 주입할 필요가 없기 때문입니다.
4. RestControllerDevice와 Swagger 충돌을 해결하기 위해 application.yml에 `override-with-generic-response: false` 옵션을 추가했습니다.
5. 배포 시 배포용 RDS 서버와 연결되도록 하기 위해 spring active profile을 `local`과 `prod` 로 나누고 프로퍼티를 다르게 설정했습니다.
5-1. Docker 이미지 생성 시 `prod` 프로필로 생성할 수 있도록 Dockerfile를 변경했습니다. 
6. CD 워크플로우에 RDS 관련 환경 변수를 추가했습니다. 
6-1. EC2 인스턴스 내부의 docker-compose 파일들에도 모두 동일하게 추가했습니다.
> 🔔 인프라 내부의 파일들을 원활히 관리하기 위해 노션에 **파일 정보와 최근 수정일을 관리할 수 있는 데이터베이스**를 구성했습니다.  (`AWS EC2 내부 파일 정보`  페이지  참고)
---
1. 이 서비스에서는 accessToken을 **Authorization** 헤더가 아닌 **Cookie** 헤더에서 가져오기 때문에 메서드에 붙인 `@SecurityRequirement` 는 …
=> [Feat] 농작업 삭제 및 Swagger 에서 memberId 파라미터 숨김 처리

backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Member.java
- close #141
---
Member의 refreshToken 데이터 타입이 binary(16) 라서 UUID가 저장되지 않는 오류가 있었습니다.
- Member의 refreshToken 데이터 타입을 **binary(16) -> VARCHAR(36)**으로 변경했습니다.
---
없습니다. 
---
=> [Fix] Member의 refreshToken 데이터 타입을 binary(16) -> VARCHAR(36)으로 변경

.github/workflows/frontend-cd.yml
- close #138 
---
https://pnpm.io/continuous-integration
npm -g install pnpm을 해도 설치가 안된다는 오류가 떠서 확인해보니 pnpm 공식 문서를 확인해보았는데, 
- name: Setup Node.js
uses: actions/setup-node@v4
with:
node-version: 22
- name: Install PNPM
uses: pnpm/action-setup@v2
깃허브액션 사용 시 npm -g i pnpm이 아니라 pnpm/action-setup@v2을 이용해 pnpm을 설치할 수 있다고 하네요.
수정 후 깃허브 레포 시크릿 키가 있는지 확인하는 코드도 추가해보았습니다.
포크 한 개인 레포에서는 잘 되었는데 과연 여기서도 잘 될 것인지...? 두근두근
---
---
---
=> [fix] 프론트엔드 cd pnpm 설치 에러 수정, 시크릿 키 테스트용 코드 추가

frontend/src/pages/weatherBoardPage/WeatherBoardPage.style.ts, frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx, frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.style.ts, frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.tsx, frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.style.ts, frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.tsx, frontend/src/pages/weatherBoardPage/utils/uvUtil.ts
- close #54 
---
- WeatherBoardUV 컴포넌트 레이아웃 및 스타일링
- `utils` > `uvUtil.ts` - UV값에 따라서 level과 색상 리턴 함수 구현
- 일일 온도 `WeatherBoardTemperature` 스타일 분리
---
https://github.com/user-attachments/assets/99637994-5792-4d86-acdc-75d03e30b39d
---
특별히 없습니다! 한번 보시구 코멘트 할 거 있으면 해주세요!
---
=> [Feat] 날씨 정보 페이지 - 일일 최고 자외선 UI 구현

frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx, frontend/src/pages/homePage/utils/updateBlockWorkTime.ts
- close #144
---
https://github.com/user-attachments/assets/329c791b-d3e7-4859-8ce8-f14453232ba7
현재 분이 30분일 때, 31분으로 이동 시 시간도 함께 증가하는 문제가 있었습니다.
ex) 시간이 6:30분일 때 6:31이 되지 않고 바로 7:31로 넘어감
현재 시간을 position.x를 기반으로 업데이트하는데, Math.round를 반올림을 하여
650->651로 넘어갈 때 반올림이 되어 700이 되는 문제 였습니다.
Math.round 삭제했습니다
---
https://github.com/user-attachments/assets/886e6093-9950-4f46-a43b-dd58245cae9d
---
---
=> [Fix] 드래그 시 시간 업데이트가 제대로 되지 않는 오류 해결

frontend/src/constants/workScheduleData.ts, frontend/src/contexts/useWorkBlocks.ts, frontend/src/hooks/dnd/useRevertPosition.ts, frontend/src/hooks/useResizeCollision.ts, frontend/src/pages/homePage/components/registerWorkContainer/RegisterWorkContainer.tsx, frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts, frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx, frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.style.ts, frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.tsx, frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx, frontend/src/pages/homePage/hooks/useChangeTimeByResize.ts, frontend/src/pages/homePage/hooks/useResize.ts, frontend/src/pages/homePage/utils/getInitialWorkBlocks.ts, frontend/src/types/workCard.type.ts, frontend/src/utils/animateBlock.ts, frontend/src/utils/collisionUtils.ts
- close #147 
---
- 렌더링 횟수를 줄이기 위해 workBlocks를 setState로 관리하고, 현재 드래그 중인 아이템을 draggingItem라는 state로 따로 관리하여 드래그 중일 때는 draggingItem만 업데이트하는 로직을 구상했었습니다.
- 다만 그렇게 하니 충돌 처리 시 마우스를 놓으면 draggingItem의 position이 업데이트되어야하는데, setWorkBlocks 후에 setDraggingItem이 실행되니 draggingItem의 업데이트가 약간..! 늦어져 애니메이션이 자연스럽게 이뤄지지 않고 잠깐 잔상이 보이는 문제가 있어, draggingItem을 state로 관리하지 않고 workBlocks에서 id로 find해서 찾는 로직으로 복구했습니다
기능 개발하면서 일어나는 문제의 70퍼센트가 setState의 상태 동기화 문제인 것 같은데 어렵네요...
TODO
1. 이동 시 y축 고정시키기
2. 처음 데이터 렌더링 시 startTime, endTime 겹치는 부분 계산해서 y축 변경하기
---
https://github.com/user-attachments/assets/b0ebb8e8-8845-450a-92a0-8f384bc686c9
---
---
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 …
=> [Feat] dnd 충돌 감지 및 충돌 시 겹치지 않는 위치로 이동

backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthController.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/dto/response/LoginResponse.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthControllerTest.java
- close #255
---
- 로그인 Response에 사용자 nickname 을 추가했습니다.
- `AuthTokens` 클래스 객체를 반환하지 않고 `LoginResponse` Dto를 반환하도록 개선했습니다.
---
```json
{
"code": 200,
"msg": "요청이 성공적으로 처리되었습니다.",
"data": {
"nickname": "농부킹",
"accessToken": "eyJhbGciOiJIUuYWdpIiwiaWF0IjoNzV9.DDA6RZmjmfcJmcPtkcfMK6PGRF7chjiT3r9VVqiaVFM(생략)",
"refreshToken": "ad88-4770f3ec(생략)"
}
}
```
---
없습니다.
---
=> [Feat] 로그인 Response에 사용자 nickname 추가

frontend/src/apis/weather.api.ts, frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx, frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.tsx, frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.tsx
- close #285 
---
- 자외선 및 일출몰 API 정의
- API 연동 및 데이터 적용
- 자외선, 일출몰 컴포넌트 props 제거
---
https://github.com/user-attachments/assets/8de4073d-48d4-48c0-aa6c-8e6570c85a97
---
1. 그... 일단은 각각 컴포넌트의 useEffect 안에서 api를 호출하고 있는데 이게 좋은건지 아니면 부모에서 한번에 useEffect안에서 호출하고 props로 넘겨주는게 좋을지 모르겠슴다...
2. API response로 데이터가 불러와지기 전에 렌더링되면서 애니메이션이나 데이터 로딩이 안 되는 문제가 있습니다.. 이것도 나중에 고칠게요... 기록해두겠습니당...
---
=> [Feat] 날씨 정보 페이지 - 자외선 및 일출몰 API 연동

backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthController.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/dto/request/LoginRequest.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/exception/MemberResponseStatus.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/controller/MyWorkController.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/DeleteMyWorkRequest.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ModifyMyWorkRequest.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/RegisterMyWorkRequest.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/WorkResponseStatus.java
- close #261 
---
1. `@Validated`를 사용하면서 request로 들어오는 필드가 null, blank일 경우 던져지는 반환 에러 code는 무조건 400이었습니다. 이를 세분화하고자 `@Validated`를 사용하지 않고 dto 내에 `validate()` 메서드를 구현했습니다. 
2. 에러 코드 명세를 [노션 페이지](https://www.notion.so/250e13d978228048878aeb9980dfcfa5?source=copy_link)에 작성했습니다.
---
필드 검증 용도 정도는... dto가 셀프로 메서드를 가지고 있어도 괜찮겠지요...?
---
=> [Feat] 요청 값이 null인 경우에 code 세분화

backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/enums/WeatherCondition.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/ShortTermWeatherForecast.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/Briefing.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/LinePoint.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/util/WeatherRiskIntervalMerger.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
- close #258 
---
1. 홈페이지 기상 그래프 시작 시간을 현재 시각 기준으로 지난 시간 중 가장 큰 시간으로 수정 (현재 시간이 12시 30분이면 12시부터 시작)
2. 홈페이지 기상 요약 API에서 '폭염' 카테고리도 필요하다고 해서 추가했습니다. 기준은 33도 이상입니다. 
3. 홈페이지 기상 리스트 시작 시간을 현재 시각 기준으로 지난 시간 중 가장 큰 시간으로 수정 (현재 시간이 12시 30분이면 12시부터 시작)
---
딱히 없습니다!
---
=> [Feat] 기상 그래프 & 리스크 조회 API 수정

backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetTemperatureResponse.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/DashboardWeatherForecast.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/DashboardWeatherForecastId.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/DashboardWeatherForecastRepository.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
- close #291 
---
1. 날씨 정보 페이지에서 보여질 시간별 기온 그래프 조회를 위한 API를 구현했습니다.
2. 이 정보를 계산해두기 위한 Batch Job을 새로운 이슈로 생성하고 구현했습니다. [PR](https://github.com/softeerbootcamp-6th/Team1-ImSnacks/pull/314#issue-3327309815)
3. 코드의 깔끔함을 위핸서 Response Dto 안에 from 정적 팩토리 메소드를 생성했습니다. 
4. 테스트 코드를 작성했습니다. 
---
Entity에서 정보를 뽑아서 Dto를 만드는 로직을 Stream의 map을 사용했는데 
이걸 람다 함수로 구현하면 내부 코드가 지저분해질 것 같아서 response dto의 정적 팩토리 메소드를 사용했습니다. 
response dto 내부에 이런 로직을 넣어도 되는지에 대해서는 논의가 필요할 것 같습니다. 
---
=> [Feat] 시간별 기온 조회 API 구현

backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthController.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/repository/MemberRepository.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthServiceTest.java
- close #406
---
1. refreshToken으로 accessToken과 refreshToken을 재발급받는 기능을 구현했습니다.
- 반환 형식은 로그인 응답과 같습니다.
- 요청 시 헤더에 `refreshToken` 키 값으로 토큰을 담도록 했습니다.
---
없습니다.
---
=> [Feat] accessToken reissue 기능

backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthController.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/dto/response/LoginResponse.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/auth/controller/AuthControllerTest.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthServiceTest.java
- close #418
---
1. accessToken 재발급 시 refreshToken을 쿠키로 보내도록 변경했습니다.
2. 로그인을 할 때도 body에 refreshToken을 담는 것이 아니라 cookie에 담도록 했습니다. (만료기한 3일) 
---
없습니다. 
---
=> [Fix] accessToken 재발급 시 refreshToken을 쿠키로 보내도록 변경

backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
- close #421
---
refreshToken cookie에 httpOnly true로 설정했습니다.
---
없습니다. 
---
=> [Fix]  refreshToken cookie에 httpOnly 설정

backend/src/main/java/com/imsnacks/Nyeoreumnagi/damage/pest/package-info.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/damage/pest/service/PestService.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/exception/CropResponseStatus.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/pest/service/PestServiceTest.java
- close #399 
---
CropResponseStatus 추가
CropResponseStatus.MY_CROP_NOT_YOURS: 6002, 요청자에게 등록된 myCropId가 아닌 경우.
병해충 리스크 요청의 myCropId가 요청자의 소유가 아닌 경우, MY_CROP_NOT_YOURS(6002) 예외를 반환합니다.
---
---
---
=> [Fix] 요청의 MyCropId가 요청자의 소유가 아닌 경우 예외 처리

backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java
- close #438
---
accessToken 재발급 시 refreshToken도 저장했습니다.
---
없습니다. 
---
=> [Fix] accessToken 재발급 시 refreshToken도 저장

batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/SchedulingConfig.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/WeatherJobConfig.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/ShortTermWeatherForecast.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/ShortTermWeatherForecastShadow.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/WeatherRisk.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/entity/WeatherRiskShadow.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/repository/ShortTermWeatherForecastShadowRepository.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/repository/WeatherRiskRepository.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/common/repository/WeatherRiskShadowRepository.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/ShadowTableInitTasklet.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/writer/WeatherWriter.java, batch/src/main/resources/application.yml
- close #440 
- close #441 
---
1. ShortTermWeatherForecast 엔티티의 shadow 엔티티 및 repository 인터페이스 생성
2. WeatherRisk 엔티티의 shadow 엔티티 및 repository 인터페이스 생성
3. 단기예보 batch writer에서 shadow table을 update하도록 수정
4. 단기예보 batch before step으로 shadow table 없으면 create 하도록 step 추가
5. 단기예보 batch after step으로 shadow table rename 하는 메소드 오버라이딩
---
다음 테이블이 추가적으로 생성됩니다. 
1. entity명 그대로인 table : 실제 api server가 data를 읽는 테이블입니다.
6. entity명 + backup : 배치로 업데이트 하기 이전 정보를 가지고 있는 테이블입니다. 
7. entity명 + shadow : 배치가 업데이트 하는 테이블이고, 배치가 무사히 업데이트하면 rename 됩니다. 
---
단기예보 논리적 오류는 별도의 이슈를 생성하고 해결하도록 하겠습니다. 
---
* P3 : 이런 방법도 있을 것 같아요~ 등의 …
=> [Refactor] 단기예보 batch Writer에서 shadow table을 update하도록 수정

backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
- close #464
---
기존에는 memberId와 id로 myWork를 바로 찾고 없으면 예외를 반환했습니다. 원인은 모르겠으나 데이터베이스에 제대로 있는 레코드를 못찾고 있어서 일단 Id로 조회 후에 memberId를 비교하는 걸로 로직을 변경했습니다.
---
없습니다. 
---
=> [Fix] findByIdAndMember_Id() -> findById() 후 memberId 동일성 검증

frontend/src/components/common/PortalComponent.tsx, frontend/src/components/common/PortalToolTip.tsx, frontend/src/components/toolTip/ToolTip.tsx, frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts, frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx, frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.style.ts, frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.tsx, frontend/src/pages/homePage/utils/work/getInitialWorkBlocks.ts
- close #473
---
- 현재보다 이전 시간에 작업하기로 등록된 작업일정의 경우 작업 정보 텍스트를 맨 오른쪽에 뜨게 하고 마우스 호버 시 전체 텍스트를 확인할 수 있도록 구현했습니다
- 구현되어있는 ToolTip 컴포넌트를 감싸서 createPortal로 적용할 수 있는 컴포넌트인 PortalToolTip을 구현했습니다
---
스크린샷에서 현재 시간은 서버 문제때문에 안뜨고 있어여
---
overflow hidden때문에 잘려서 createPortal썼습니당
---
=> [Feat] 현재보다 이전 시간인 작업 일정 표시

backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/WeatherRisk.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
- close #481 
---
Batch 프로젝트에서는 WeatherRisk 엔티티에 fcst_date 필드가 없어서 batch Job이 동작하면서 RDS의 테이블에 해당 컬럼이 지워진 것 같습니다.
그런데 API Server에서는 WeatherRisk에 fcst_date 필드가 남아있어서 엔티티를 읽을 수 없다는 500 error가 발생했습니다.
일단은 임시방편으로 RDS의 WeatherRisk에 fcst_date 컬럼을 추가하여 해결했습니다. 
1. api server 프로젝트의 WeatherRisk 엔티티에서 fcst_date 필드를 지웠습니다. 
---
제가 확인하긴 했는데 다른 엔티티도 동일한지 확인해주시면 감사하겠습니다. 😁
---
=> [Hotfix] Batch 프로젝트와 api server 프로젝트 간 entity 불일치로 인한 오류 해결

batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/WeatherReader.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/writer/WeatherWriter.java
- close #455 
---
1. 단기예보 batch에서 job 실패시 shadow table로 rename 되는 오류를 해결했습니다. 
2. 즉 단기예보 job이 실패하면 이전 update 날씨 데이터가 보여집니다. 
---
없습니다!
---
=> [Fix] Batch Job 실패했을 때 shadow table이 rename되지 않도록 수정

backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/util/WorkScheduleCalculator.java
- close #500
---
1. 드디어 원인을 발견했습니다....
`ShortTermWeatherForecast`를 시간 순으로 정렬 후에 추천 시간대를 구성하는 로직인데, `fcstTime`이 hour(int) 로직을 제대로 변경하지 않아서 정렬이 다음과 같이 hour 기준으로만 되고 있었습니다.
```java
"2025-08-24T01:00"
"2025-08-25T01:00"
"2025-08-24T02:00"
"2025-08-25T02:00"
```
이를 날짜, 시간을 모두 고려하여 정렬하도록 고쳤습니다.
2. 추천 시간대가 현재 시각부터 23시간 이후 내로 구성되도록 아래와 같이 필터링했습니다.
```java
List<ShortTermWeatherForecast> sortedForecasts = forecasts.stream()
.filter(forecast -> forecast.getFcstTime().isAfter(requestDateTime.minusHours(1)) && forecast.getFcstTime().isBefore(requestDateTime.minusHours(2).plusDays(1)))
```
예를 들어 **2025년 8월 24일 2시 14분**에 요청을 보낸다면 forecast의 FcstTime이
**2025년 8월 24일 1시 14분** (requestDateTime.minusHours(1))보다 이후이고, **2025년 8월 24일 23시 14분** (requestDateTime.minusHours(2).plusDays(1))) 보다 이전인 forecast 들만 …
=> [Fix] 농작업 추천 시 단기 예보 정렬 오류 해결

frontend/src/pages/homePage/components/registerWorkContainer/RegisterWorkContainer.style.ts, frontend/src/pages/homePage/components/registerWorkContainer/RegisterWorkContainer.tsx, frontend/src/pages/homePage/components/workCell/WorkCell.style.ts, frontend/src/pages/homePage/components/workCell/WorkCell.tsx, frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.style.ts, frontend/src/pages/homePage/hooks/work/useCreateWorkBlock.ts, frontend/src/pages/homePage/hooks/work/useWorkBlocks.ts, frontend/src/pages/myFarmPage/components/myCropInfo/MyCropInfo.tsx, frontend/src/pages/myFarmPage/components/myFarmHeader/MyFarmHeader.style.ts
- close #493
---
- 원래 작업/추가 시 재정렬과 애니메이팅 블록 이동이 안되었는데 되도록 추가했습니다
- 작업 블록의 시간대가 미묘하게 안맞아서 수정했습니다
- 내농장 툴팁 방향 수정
- WorkCell에 hover 시 색이 변하고 작업일정을 드래그해서 추가하라는 문구가 떴는데, Hover 스타일이 들어가니 해당 공간을 클릭해야할 것같다는 피드백이 있어 hover을 삭제하고 안내 문구 툴팁을 추가했습니다 
- WorkCell 간 간격이 크니 시간이 정확히 맞지 않는 것 처럼 보여 gap을 줄이고 width를 늘렸습니다
수정 전: WorkCell의 밖으로 넘어가야 20시에 도달
수정 후: 17시에 시작해서 20시에 끝나는 게 그리드에 거의 맞는 것 처럼 보임
---
https://github.com/user-attachments/assets/3cb4a2ea-d604-4aab-819c-ce57f6d312bf
정렬 애니메이션 추가 후, workCell 수정 전
WorkCell 수정 후, 툴팁 추가
내농장 툴팁 방향 수정
---
useWorkBlocks 훅 내에 data fetch, 상태 관리, animating이 혼재되어있는데 어떻게 관심사 분리를 할 수 있을 지 고민입니다.
---
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 …
=> [Feat] 작업 추가/삭제 시 재정렬 및 애니메이팅 추가

backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/WorkActivityFact.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/event/MyWorkCompletedEvent.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/event/MyWorkCompletedEventListener.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/WorkActivityFactRepository.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/NearbyAggregationService.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/WorkActivityFactTest.java
- close #528
---
1. 농작업 상태를 `COMPLETED` 로 변경할 때만 `WorkActivityFact` 테이블에 insert 했었습니다. 그러나 상태를 다시 `INCOMPLETED` 로 바꾸면 농작업 인원 집계에서 제외해야하기 때문에 `WorkActivityFact` 에 상태 필드를 추가하고 `insert ignore` 대신 같은 키 레코드가 존재하면 insert 대신 update 할 수 있도록 쿼리 메서드를 수정했습니다.
```SQL
INSERT IGNORE INTO work_activity_fact(day, work_id, tile, member_id, created_at)
VALUES (:day, :workId, :tile, :memberId, now())
```
```SQL
INSERT INTO work_activity_fact(day, work_id, tile, member_id, work_status, created_at)
VALUES (:day, :workId, :tile, :memberId, :workStatus, now())
ON DUPLICATE KEY UPDATE
work_status = VALUES(work_status)
```
2. 로컬과 배포 디비 모두 `Farm`의 `location` 필드가 위경도가 반대로 저장돼있었습니다. 아래 SQL로 일괄 수정했습니다.
```SQL
UPDATE farm
SET location = POINT(ST_Y(location), ST_X(location));
```
3. 농작업 추천 시 `COMPLETED` 인 농작업 인원만 집계할 수 …
=> [Feat] 농작업 상태를 다시 `INCOMPLETED`로 변경하면 집계에서 제외되도록 구현

backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/Briefing.java, backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java, backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
- close #509 
---
**문제 상황 예시**
현재 시각: 17시 42분
브리핑에 표시할 기상 리스크 기간(WeatherRisk 레코드): 16시-20시
기댓값: "오후 5시부터 오후 8시까지 <기상예보>"
실제값: "오후 4시부터 오후 8시까지 <기상예보>"
**해결**
원래, 위와 같이 `WeatherRisk`가 현재 시각 이전에 시작하는 경우, 그 시작 시각을 그대로 브리핑 메시지로 전달하였습니다.
예보 그래프는 현재 시각 이후(현재 시(hour)는 포함)로 시작 시각을 수정해 전달하는데, 브리핑 메시지의 시작 시각과 불일치하는 문제가 있었습니다. 일관성을 위해 그래프와 같은 시작 시각 기준을 적용하였습니다.
---
---
---
=> [Fix] 기상 브리핑 메시지의 기상 특보 시작 시간 요건 변경

frontend/src/components/dnd/utils/isFullyOverlapped.ts, frontend/src/components/dnd/utils/resolveCollision.ts, frontend/src/constants/workTimeCoordinate.ts, frontend/src/pages/homePage/components/workCell/WorkCell.style.ts, frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.style.ts, frontend/src/pages/homePage/components/workCellsContainer/WorkCellsContainer.tsx, frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx, frontend/src/pages/homePage/hooks/work/useCreateWorkBlock.ts, frontend/src/pages/homePage/hooks/work/useWorkBlocks.ts, frontend/src/pages/homePage/utils/work/sortWorkBlocks.ts, frontend/src/store/useMaxLayerStore.ts
- close #533
---
- 정각에 refetch
- 작업 일정 추가 시 놓을 수 있는 위치가 없을 경우 가능한 다른 위치에 등록을 시켜버리는 플로우가 정말 맞는 건지에 대한 고민을 많이 해봤는데요...
현재 기획상 같은 시간대에 작업은 3줄까지만 등록이 가능하고, 그 이후는 같은 시간대에 등록이 불가합니다.
그리고 dnd를 쓰는 다른 서비스도 많이 찾아봤는데.. 일정 등록을 하는 서비스의 경우 무한히 늘어나더라도 사용자의 등록에 한계를 두는 경우는 별로 없더라구요
drag and drop ui라는건 사용자에게 주는 자유도가 무척 중요한 ui라는 생각을 했어요.
dnd에서 가장 중요한건 사용자가 인터페이스를 원하는대로 제어하는 것이라, 정확히 원하는 시간에 일정을 등록할 수 있도록 자유도를 보장하는 게 더 중요하다는 생각을 했습니다..
서비스에서 동시대에 작업하는 걸 꼭 막아야하는 이유도 없는 것 같아서 제한을 풀고 같은 시간대에 무제한으로 등록할 수 있게 변경했습니다... 
---
https://github.com/user-attachments/assets/2e47ab83-846f-4731-b6c1-69deac364f6d
정각에 refetch는 되는데 00시에 시작했던 작업이 데이터 refetch 시 갑자기 사라지는건 확인해보니 api 문제 같아서...... 세연님꼐 여쭤보겠습니다
https://github.com/user-attachments/assets/9ac55858-d3fb-4622-8d2f-868e8fbf19a8
---
maxYlayer은 작업일정 컨테이너에만 쓰이는 부분이라 전역변수로 …
=> [Feat] 작업 일정 컨테이너 height 동적 증가 및 정각에 refetch 기능 구현

backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
- close #537 
---
단기예보 batch에서 48시간 이후 데이터까지 받도록 수정하자, 홈페이지 기상 그래프 조회 API 로직에 문제가 생겼습니다. 
24시간 이후 데이터를 가져오는 방식에 문제가 생겨서 날짜 기반으로 24시간을 계산하도록 로직을 수정했습니다. 
---
없습니다. 
---
=> [Hotfix] 기상 그래프 조회 API에서 24시간 이후 데이터까지만 조회안되는 오류 해결

frontend/src/components/dnd/draggableItem/DraggableItem.tsx, frontend/src/components/dnd/hooks/useDragBlock.ts, frontend/src/components/dnd/hooks/useResizeBlock.ts, frontend/src/pages/homePage/hooks/work/useWorkBlocks.ts, frontend/src/pages/homePage/utils/work/sortWorkBlocks.ts, frontend/src/pages/homePage/utils/work/updateBlockTimeOnServer.ts
- close #542
---
- 리액트 쿼리 적용 후 post/delete/patch 시 데이터가 업데이트 되지 않아, 다른페이지에 방문한 후 돌아오면 이전 데이터가 남아있는 문제가 있었습니다.
- 캐시 무효화를 적용했으며, dnd와 resize에 애니메이팅이 들어가기에 애니메이팅이 끝난 후 캐시 무효화를 하기위해 setTimeout으로 1초 후 캐시 무효화를 진행했습니다.
- 정각에 refetch: 작업 블록이 옆으로 이동하는 애니메이션 필요
- 그 외 추가, 수정, 삭제: setState로 직접 애니메이션 관리
애니메이팅이 되어야하는 조건이 두가지로 나뉘므로 정각에 refetch할 때만 애니메이션이 작동하고, 그 외에는 서버에서 데이터를 새로 호출받아도  불필요한 애니메이션이 실행되지 않도록 skipAnimationRef 값을 이용해 분기 처리를 했습니다.
- 시작 시간이 같은 경우 sort할 때 작업 등록 순서(id)순으로 정렬되게 정렬 조건을 추가했습니다.
---
---
---
=> [Fix] 리액트 쿼리 적용 후 post/delete/patch 시 데이터 업데이트 안됨 문제 해결

batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/AlterApiCaller.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/ImprovedApiCaller.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/processor/ImprovedWeatherProcessor.java, batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/WeatherReader.java, batch/src/main/resources/application.yml
- close #458 
---
1. 기상청 open api 실패하는 경우가 잦아서 기상청 open api가 실패했을 시 새로운 src를 호출하는 경우가 필요했습니다. 
2. 기존 processor에서 기상청 api를 호출실패했을 시 tomorrow.io 를 호출하는 AlterApiCaller 클래스를 생성했습니다.
3. 기상청 응답 DTO인 VilageFcstResponseDto 형식에 맞추는 convertToVilageFcstResponseDto 메소드를 작성했습니다. 
4. 실제로 DB에 값을 잘 받아오는 것을 확인했습니다. 
현재 흐름은 다음과 같습니다 .
기상청 단기예보 3번 시도 --> 실패시 tomorrow.io 예보 3번 시도 --> 전부 실패시 default 값 반환
---
배포할텐데 잘 동작하는지 모니터링 부탁드립니다. 
---
=> [Refactor] 기상청 단기예보 batch 실패시 tomorrow.io 호출하도록 수정

backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
- close #566 
---
startTime == endTime 인 기상 리스크는 브리핑 메시지 생성 시 무시하도록 수정하였습니다.
---
---
---
=> fix: 브리핑에서 시작시각과 종료시각이 같은 기상 리스크는 무시하도록 처리

batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/writer/WeatherWriter.java
단기예보 batch가 14시 15분에 돌면 14시 정보를 저장하지 않는 문제를 발견했습니다. 
기존 backup 테이블에서 정보를 가져오는 것으로 수정했습니다. 
---
없습니다. 
---
=> [Hotfix] 단기예보 batch 1시간 이전 정보 저장하도록 수정
