softeerbootcamp-6th/Team1-ImSnacks

- .github/workflows/close-issues-on-merge.yml
- frontend/.gitignore
- frontend/.prettierrc
- frontend/README.md
- frontend/eslint.config.js
- frontend/index.html
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/App.tsx
- frontend/src/main.tsx
- frontend/src/vite-env.d.ts
- frontend/tsconfig.app.json
- frontend/tsconfig.json
- frontend/tsconfig.node.json
- frontend/vite.config.ts
- close #7 
---
close #이슈번호로 이슈를 닫는 경우 병합되는 브랜치가 default브랜치가 아닌 경우는 close를 붙여도 이슈가 닫히지 않아서
브랜치 명이 feat/fe, fix/fe로 시작하는데 fe 브랜치로 병합될 경우, feat/be, fix/ 해당 이슈가 자동으로 닫히는 워크플로우를 작성하였습니다
실제도 작동될지는..? 테스트 해봐야됨!!
---
---
---
> [Feat] PR 병합 시 브랜치명에 따라 자동으로 이슈를 닫는 workflow 추가

- frontend/src/App.tsx
- frontend/src/layouts/Layout.tsx
- frontend/src/layouts/navBar/NavBar.tsx
- frontend/src/main.tsx
- frontend/src/routes/Router.tsx
- close #6 
---
- `Layout` 컴포넌트 제작
- `react-router` 라이브러리로 라우팅 기능 구현
- `NavBar` 컴포넌트 제작 및 url 연결
---
---
일단 스타일은 고려하지 않고 거의 날 것 수준으로 만들었습니다..
궁금하신 거나 다른 구현 방법 제안하고 싶으신거 편하게 말씀해주십시오!
> [Feat] NavBar 제작 및 라우팅 기능 구현

- frontend/src/routes/Router.tsx
- frontend/src/styles/colors.ts
- frontend/src/styles/effects.ts
- frontend/src/styles/spacing.ts
- close #4 
---
- figma에 추가된 디자인 시스템 추가
- spacing 디자인 시스템 추가
---
---
---
> [Feat] 디자인 시스템 구현: spacing, weatherboard gradient, dropshadow 추가

- backend/.deploy/deploy.sh
- backend/.deploy/nyeoreumnagi-blue-deploy.yml
- backend/.deploy/nyeoreumnagi-green-deploy.yml
- backend/.github/workflows/CD.yml
- close #27 
---
1. CD.yml 파일 작성
2. Docker container 띄우는 docker-compose 파일 작성
3. Blue-Green 무중단 배포를 위한 deploy.sh 스크립트 작성
---
없습니다.
---
> [FEAT] CD 스크립트 작성 및 blue-green 무중단 배포 스크립트 작성

- .github/workflows/CD.yml
- close #31 
---
CD 플로우에서 working directory 설정 변경
---
---
> [HOTFIX] working directory 설정 변경

- .github/workflows/CD.yml
- close #36 
---
- CD 워크플로우 경로 수정
- ec2 username 변경 (`ubuntu` -> `ec2-user`)
---
---
x
---
> [FIX] CD 워크플로우 경로 수정 및 ec2 username 변경

- .github/workflows/CD.yml
> [HOTFIX] docker build 에서 platform 설정 추가

- batch/build.gradle
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/WeatherWriter.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/dto/ShortTermWeatherDto.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/entity/ShortTermWeatherForecast.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/entity/ShortTermWeatherForecastId.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/entity/WeatherRisk.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/entity/WeatherRiskRepository.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/entity/WeatherRiskType.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/writer/repository/WeatherRepository.java
- batch/src/main/java/dto/VilageFcstResponse.java
- batch/src/main/resources/application.properties
- batch/src/main/resources/application.yml
- batch/src/test/java/com/ImSnacks/NyeoreumnagiBatch/WeatherWriterTest.java
- close #44
---
- 공공데이터포털 Open API로부터 응답받은 단기예보 날씨 데이터를 프로세싱 후에 **서비스 데이터베이스로 저장하는 `WeatherWriter`** 를 구현했습니다.
- 저장을 위해 mysql 의존성을 추가했고 테스트 데이터베이스로는 h2 의존성을 추가했습니다. 
- **processor -> writer** 전달을 위한 `ShortTermWeatherDto` 를 구현했습니다. 
- 데이터베이스에 제대로 insert가 되는지 확인하는 통합테스트를 수행했습니다.
```plain-text
ShortTermWeatherDto
├── int nx
├── int ny
├── LocalDate fcstDate
├── List<WeatherForecastByTime> weatherForecastByTimeList
│   └── WeatherForecastByTime
│       ├── int fcstTime
│       ├── double precipitation
│       ├── int temperature
│       ├── int humidity
│       └── double windSpeed
└── List<WeatherRisk> weatherRiskList
└── WeatherRisk
├── int startTime
├── int endTime
└── WeatherRiskType name
```
---
- 추후에 Batch Job 기준 전체 통합테스트를 수행해야합니다.
- [Reader 구현체 선택과정 wiki …
> [Feat] 날씨 Batch 서버 중 `ItemWriter` 기능 구현 

- .github/ISSUE_TEMPLATE/epic.yml
- close #74 
---
- #42  ⬅️  이슈처럼 **서브 이슈로 업무를 분담해야하는 큰 이슈**의 경우에는 `Feat`, `Fix` 등의 프리픽스를 부여하는 것보다 `Jira의 Epic 개념`을 사용하는 것이 더 나을 것 같다고 생각했습니다. ➡️ 따라서 이 경우에 사용할 수 있는 **Epic 용 이슈 템플릿**을 생성했습니다.
- 이를 통해 실제로 각 팀원이 할당받은 이슈와 추상적인 큰 이슈를 확실하게 분리할 수 있습니다.  
- 이 뷰에서 Epic 템플릿으로 이슈를 생성하면 다른 뷰 (Current Sprint 등) Epic 칸에서 해당 Epic 이슈를 확인할 수 있습니다.
---
없습니다. 
---
> feat: Epic 이슈 템플릿 추가

- frontend/src/pages/weatherBoardPage/WeatherBoardPage.style.ts
- frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardDust/WeatherBoardDust.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardHumidity/WeatherBoardHumidity.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardRain/WeatherBoardRain.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemparature.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardUV/WeatherBoardUV.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardWind/WeatherBoardWind.tsx
- frontend/src/routes/Router.tsx
- frontend/src/styles/commonStyles.ts
- frontend/src/styles/effects.ts
- close #56 
---
- WeatherBoardPage 구조화
- 시각화 카드 컴포넌트 분리 및 구현
- CommonStyles, FlexStyles 스타일 객체 생성
- DropShadow - Ds300 컬러코드 수정
---
---
- 지금 이렇게 보니까 모든 컴포넌트를 불러오는 부분에서 각각 하다보니까 import 줄이 좀 많네요...
```
import WeatherBoardTemparature from './components/weatherBoardTemperature/WeatherBoardTemparature';
import WeatherBoardWeekly from './components/weatherBoardWeekly/WeatherBoardWeekly';
import WeatherBoardRain from './components/weatherBoardRain/WeatherBoardRain';
import WeatherBoardHumidity from './components/weatherBoardHumidity/WeatherBoardHumidity';
import WeatherBoardWind from './components/weatherBoardWind/WeatherBoardWind';
import WeatherBoardUV from './components/weatherBoardUV/WeatherBoardUV';
import WeatherBoardDust from './components/weatherBoardDust/WeatherBoardDust';
import …
```
> [Feat] 날씨 정보 페이지 컴포넌트 분리 및 구조화, commonStyles 생성

- .github/workflows/frontend-cd.yml
- close #49
---
1. pnpm 설치
2. pnpm 빌드
3. AWS 인증
4. S3 파일 삭제 및 재업로드
5. CloudFront 캐시 무효화
---
---
현재 ci에서 할 별도의 테스트가 없고 cd 파일 내에서 빌드를 하고 빌드 테스트까지 되기에 cd.yml 파일만 생성하였습니다.
현재 개인 계정으로 배포했는데, s3만 쓰면 요금 청구가 안될 줄 알았는데 조금 되길래..? 테스트만 해보고 제대로 배포되면 IAM 권한 요청할까 싶어요..
---
> [Feat] 프론트엔드 배포 cd 파일 

- backend/build.gradle
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Member.java
- backend/src/main/resources/application.yml
- close #109 
---
ERD의 Member 릴레이션에 대응되는 Member 클래스 입니다.
---
---
필드, 클래스 어노테이션이 적절한지 확인 부탁드립니다.
---
> [Feat] Member entity 추가

- .github/workflows/CD.yml
- backend/.deploy/nyeoreumnagi-blue-deploy.yml
- backend/.deploy/nyeoreumnagi-green-deploy.yml
- close #122 
---
1. CD action 스크립트에서 jwt 관련 환경변수를 github secret 에서 가져오도록 수정
2. blue, green 버전을 띄우는 docker compose 파일에서 환경변수를 가져오도록 수정
---
환경변수가 빠진 부분이 있는 확인 부탁드립니다. 
---
> [Fix] 환경 변수 추가로 인한 CD action 오류 해결

- backend/.deploy/nyeoreumnagi-blue-deploy.yml
- backend/.deploy/nyeoreumnagi-green-deploy.yml
- close #122 
---
docker compose에서 환경변수를 잘못 주입하고 있었네요...? 죄송합니다. 
---
---
> [Hotfix] docker compose에서 환경변수 잘못 넣은 오류 해결

- frontend/src/pages/weatherBoardPage/components/temperatureDot/TemperatureDot.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardTemperature/WeatherBoardTemperature.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.style.ts
- frontend/src/pages/weatherBoardPage/components/weatherBoardWeekly/WeatherBoardWeekly.tsx
- frontend/src/pages/weatherBoardPage/components/weeklyContent/WeeklyContent.style.tsx
- frontend/src/pages/weatherBoardPage/components/weeklyContent/WeeklyContent.tsx
- close #51
---
- WeatherBoardWeekly 컴포넌트 구현 및 스타일링
- WeeklyContent 컴포넌트 구현 및 스타일링
- 최고 온도 관련 컴포넌트 이름 수정
- 기존에는 weekly라는 키워드를 붙였는데 엄밀히 말하면 하루에 대한 데이터이기 때문에 맞지도 않고 7일 날씨 관련 컴포넌트와 혼동될 것 같아서 수정했습니다!
- 앞으로도 각 시각화마다 관련된 컴포넌트 명명 규칙은 이런 식으로 하려고 해요
```
- WeatherBoardTemperature 관련 -> temperatureDot
- WeatherBoardWeekly 관련 -> weeklyContent
```
---
---
특별한 건 없고 제가 이번에 하면서 스타일링 방식을 바꾼게 있는데 같이 적용하면 좋을 것 같아서 공유해드려요!
```js
// 변경 전
<div css={css`
${CommonStyles.weatherBoardContainer}
${S.WeatherBoardWeekly}
padding: ${Spacing.Spacing400};
...
`}>
// 변경 후
<div css={S.WeatherBoardWeekly}>
const WeatherBoardWeekly = css`
${CommonStyles.weatherBoardContainer}
${FlexStyles.flexColumn};
padding: ${Spacing.Spacing400};
...
`;
```
기존에 저희가 같은 level의 스타일 객체를 적용하는 `S.style` 말고도 다른 공용 스타일 객체나 별도 자잘한 스타일링까지 같이 하게 되면 …
> Feat: 날씨 정보 페이지 - 7일 날씨 UI 구현

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/util/TimeValidator.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/dto/request/ResisterMyWorkRequest.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWork.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/work/entity/MyWorkTest.java
- close #128
---
사용자가 농작업을 등록할 때 `startTime`, `endtime` 을 "HHmm" 으로 받는데 이를 LocalDateTime으로 저장할 수 있도록 변경했습니다.
---
없습니다. 
---
> [Fix] MyWork에 저장하는 시간 타입을 String("HHmm") 에서 LocalDateTime으로 변경

- .github/DISCUSSION_TEMPLATE/공지.yml
- .github/DISCUSSION_TEMPLATE/논의 공간.yml
- .github/DISCUSSION_TEMPLATE/아이디어.yml
- .github/DISCUSSION_TEMPLATE/투표.yml
- close #150
---
GitHub Discussion 용 템플릿들을 카테고리별(`공지`, `논의 공간`, `아이디어`, `투표`)로 추가했습니다.
---
추가하면 좋을만한 항목이 있다면 알려주세요 ~ 😄
---
> [Docs] GitHub Discussion 용 템플릿 추가

- .github/DISCUSSION_TEMPLATE/공지.yml
- .github/DISCUSSION_TEMPLATE/논의 공간.yml
- .github/DISCUSSION_TEMPLATE/아이디어.yml
- .github/DISCUSSION_TEMPLATE/투표.yml
- close #161
---
이젠 템플릿이 꼭 적용되길 빕니다...
---
x
---
> fix: description 을 큰따옴표로 묶음

- frontend/src/assets/icons/flat/SunEffect.svg
- frontend/src/assets/icons/flat/index.ts
- frontend/src/pages/weatherBoardPage/WeatherBoardPage.tsx
- frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.style.ts
- frontend/src/pages/weatherBoardPage/components/weatherBoardSunset/WeatherBoardSunset.tsx
- frontend/src/pages/weatherBoardPage/hooks/useSunsetAnimation.ts
- frontend/src/pages/weatherBoardPage/utils/sunsetUtil.ts
- close #55
---
- SunEffect.svg 파일 추가
- WeatherBoardSunset 컴포넌트 구현
- sunsetUtil 함수 구현
- useSunsetAnimation hook 구현
---
https://github.com/user-attachments/assets/83f5b7db-042f-4871-b402-af9ced504190
---
은진님.. 이슈 해결하느라 바쁘겠지만 리뷰 부탁드려요..
---
> [Feat] 날씨 정보 페이지 - 일출/일몰 컴포넌트 UI 구현

- .github/workflows/frontend-cd.yml
- close #204
---
id-token permission을 넣으라고 해서 추가했습니다...
---
---
---
> [Fix] frontend-cd workflow id-token permission 추가

- .github/workflows/backend-ci.yml
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/lifecycle/LifeCycleResolver.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/lifecycle/entity/LifeCycle.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/repository/LifeCycleRepository.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/lifecycle/LifeCycleResolverTest.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/util/WorkScheduleCalculatorTest.java
- close #214 
- close #220 
---
backend-ci.yml 로 자동화된 테스트가 PR요청 브랜치의 최신 파일을 읽지 못 하는 문제가 있었습니다.
기본적으로 PR base branch(be) 상에서 실행되는 pull_request_target 대신, PR merge branch(feat/be-xx)상에서 실행되는 pull_request로 트리거를 변경했습니다.
따라서 PR요청 브랜치의 최신 파일 기준으로 CI가 실행될 수 있습니다.
---
---
---
> [Fix] CI 오류 수정

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/config/WebConfig.java
- close #232
---
`DELETE`, `OPTIONS` 에서 cors 정책이 적용되는 문제를 해결했습니다. 
---
x
---
> [Fix] `DELETE`, `OPTIONS` 에서 cors 정책이 적용되는 문제 해결

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetFcstRiskResponse.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetSunRiseSetTimeResponse.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherBriefing.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherBriefingResponse.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherConditionResponse.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetWeatherGraphResponse.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/DashboardTodayWeatherRepository.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/util/WeatherRiskIntervalMerger.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
- close #228 
---
1. DashboardTodayWeather 테이블에서 일출몰 정보만 projection 
2. 테스트 코드 작성
---
그 projection을 하다 보니 queryDSL의 필요성을 느꼈달까... 다들 어떻게 생각하시나요 
---
> [Feat] 일출몰 시각 조회 API 구현

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/pages/homePage/components/headline/Headline.tsx
- frontend/src/store/useTimeStore.ts
- frontend/src/store/useUserStore.ts
- frontend/src/store/useWeatherConditionStore.ts
- close #252 
---
- zustand 설치
- 전역 상태 관리 구축
- useUserStore
- useTimeStore
- useWeatherStore 
은진님 말대루 관심사 분리 했습니당~ㅎ
---
---
pnpm install 하고 개발 진행해주세요~!
---
> [Feat] zustand를 활용한 환경 세팅 및 전역 데이터 관리 #252

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/MyWorkService.java
- close #270
---
완료되지 않은 농작업도 삭제할 수 있도록 수정했습니다.
---
없습니다.
---
> [Fix] 완료되지 않은 농작업도 삭제할 수 있도록 변경

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/member/entity/Farm.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetSevenDaysForecastResponse.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/SevenDayWeatherForecast.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/entity/SevenDayWeatherForecastId.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/SevenDayWeatherForecastRepository.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/member/MemberServiceTest.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherBriefingTest.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/entity/SevenDayWeatherForecastTest.java
- close #267
---
1. **날씨 정보** 페이지에서 사용할 7일 기상 예보 조회 기능을 구현했습니다.
2. 사용자의 `Farm` 에서 예보구역코드를 가져올 수 있도록 `Farm`에 `midTempRegionCode` 필드를 추가했습니다.
- 지금은 연관관계가 아닌 그냥 문자열 필드인데 연관관계를 맺어야할지, 구성을 어떻게 할지 고민 중에 있습니다.
- 회원가입할 때 사용자 정보를 어떻게 처리하느냐와 관련이 있을 것 같습니다.
- 필드 추가에 따라 `WeatherBriefingTest` 에서 Farm 목데이터 생성하는 부분을 수정했습니다.
3. 7일 기상 예보 조회 결과가 7개가 아닐 경우 `INVALID_SEVEN_DAY_FORECAST_COUNT` 예외를 반환하도록 했습니다.
4. **7일 예보 요일 계산 로직**을 엔티티 내 비즈니스 로직 메서드로 추출하고 단위 테스트를 수행했습니다.
---
```json
{
"code": 200,
"msg": "요청이 성공적으로 처리되었습니다.",
"data": [
{
"dayOfWeek": "오늘",
"weatherCondition": "LESS_CLOUDY",
"maxTemperature": 32,
"minTemperature": 25
},
{
"dayOfWeek": "내일",
"weatherCondition": "RAIN",
"maxTemperature": 32,
"minTemperature": 24
},
{
"dayOfWeek": "일요일",
"weatherCondition": "CLOUDY",
"maxTemperature": 32, …
```
> [Feat] 7일 기상 예보 조회 기능

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/controller/WeatherController.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetDailyMaxPrecipitationResponse.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/dto/response/GetPrecipitationResponse.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/exception/WeatherResponseStatus.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/repository/DashboardTodayWeatherRepository.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/projection_entity/PrecipitationInfo.java
- backend/src/test/java/com/imsnacks/Nyeoreumnagi/weather/WeatherServiceTest.java
- close #290 
---
1. 날씨 정보 페이지에서 보여질 일일 최고 강수량 조회 API를 구현했습니다. 
2. 테스트 코드를 작성했습니다. 
---
기존 조회 API와 다를바가 없어 요구사항은 딱히 없습니다. 
---
> [Feat] 일일 최고 강수량 조회 API 구현

- frontend/src/pages/weatherBoardPage/components/weatherBoardWind/WeatherBoardWind.style.ts
- frontend/src/pages/weatherBoardPage/components/weatherBoardWind/WeatherBoardWind.tsx
- close #333 
---
각도에 따른 Keyframes생성 함수와 스타일 구현해두었고 데이터 로드된 후 애니메이팅 되도록 했습니다.
---
https://github.com/user-attachments/assets/93bd305b-1a15-4cf3-8c5b-7929d2c93dd9
---
딱히 없습니당.
---
> [Feat] 최고 풍속 화살표 아이콘 회전 애니메이션 구현

- frontend/src/pages/homePage/components/customizedTootip/CustomizedTooltip.tsx
- frontend/src/pages/homePage/components/mainLineChart/MainLineChart.style.ts
- frontend/src/pages/homePage/components/mainLineChart/MainLineChart.tsx
- frontend/src/pages/homePage/components/portalTooltipWrapper/PortalTooltipWrapper.tsx
- close #345 
---
- createPortal을 이용한 툴팁 최상단 표시를 위해 PortalTooltipWrapper 컴포넌트 구현
- CustomTooltip 마우스 중앙 정렬을 위한 x,y 파라미터 추가 및 스타일링
- MainChart 스타일에 불필요한 background linear-gradient 제거
---
https://github.com/user-attachments/assets/34da40c7-33c1-43ed-b8c5-ef0e3bb57635
---
딱히 업습니당!
---
> [Feat] 홈페이지 - 메인 그래프 Tooltip 관련 이슈 해결

- frontend/src/apis/damage.api.ts
- frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.tsx
- frontend/src/pages/homePage/components/damagePests/DamagePests.tsx
- frontend/src/pages/homePage/hooks/useDamagePests.ts
- frontend/src/pages/homePage/hooks/useDamagePestsUI.ts
- close #416
---
- 병충해 api 연동했습니다
- 버튼 클릭할때마다 api가 호출되는데 빠른 시간 안에 호출할 경우 이전 데이터 들고있다가 보여주는 쪽으로 최적화 필요..
---
https://github.com/user-attachments/assets/0797c3c3-147c-431c-aa36-775ec6d6bf66
---
브랜치명을 실수로 fear/fe-416으로 팠어요
---
> [Feat] 병충해 api 연동

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
- close #423 
---
refreshToken cookie에 sameSite none 을 설정했습니다.
---
없습니다.
---
> [Fix] refreshToken cookie에 sameSite none 설정

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
- close #428
---
cookie secure true 설정한다.
---
없습니다.
---
> [Fix] cookie secure true 설정

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/response/ResponseUtil.java
- close #430
---
cookie 생성 시 sameSite를 "Lax"로 설정했습니다.
---
없습니다. 
---
> fix: cookie 생성 시 sameSite를 "Lax"로 설정

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/common/auth/service/AuthService.java
- close #443
---
accessToken 재발급 시 refreshToken 오류를 해결했습니다. 
---
없습니다. 
---
> [Fix] accessToken 재발급 시 refreshToken 오류 해결

- backend/src/test/java/com/imsnacks/Nyeoreumnagi/pest/service/PestServiceTest.java
- close #443
---
PestServiceTest 오류를 해결했습니다.
---
없습니다.
---
> fix: PestServiceTest 오류 해결

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/util/WorkScheduleCalculator.java
- close #449
---
농작업 추천 시간대 최대값을 4시간으로 제한했습니다.
---
코드가 조금 복잡합니다. ㅠㅠㅠ 
---
> [Fix] 농작업 추천 시간대 최대값을 4시간으로 제한

- frontend/src/App.tsx
- frontend/src/apis/http.ts
- frontend/src/components/common/ProtectedRoute.tsx
- frontend/src/layouts/Layout.tsx
- frontend/src/pages/accessDeniedPage/AccessDeniedPage.style.tsx
- frontend/src/pages/accessDeniedPage/AccessDeniedPage.tsx
- frontend/src/pages/homePage/HomePage.tsx
- frontend/src/pages/homePage/components/mobileTodo/MobileTodo.style.ts
- frontend/src/pages/homePage/components/mobileTodo/MobileTodo.tsx
- frontend/src/pages/notFoundPage/NotFoundPage.style.tsx
- frontend/src/pages/notFoundPage/NotFoundPage.tsx
- frontend/src/routes/Router.tsx
- frontend/src/store/useIsMobileStore.ts
- close #383 
---
- isMobile 상태 전역 상태 관리
- NotFoundPage, AccessDeniedPage 구현
- ProtectedRoute 컴포넌트 구현
- 페이지별 라우팅 접근 제한 적용
- MobileTodo 리스트 없을 때 텍스트 표시
---
https://github.com/user-attachments/assets/4cd63529-29a3-42e8-9621-34d0285ca00a
---
1. 일단 루트에 있는 components/common 에다가 ProtectedRoute 컴포넌트를 넣어놨는데 저희가 루트에 있는 components 파일은 공용으로 사용 가능한 애들을 넣어놓기로 했잖아요. 그런 의미에서 common이라는 폴더를 또 만드는게 맞는 건지 의문이 듭니다..
2. 처음 렌더링 할 때 화면 크기에 따라서 isMobile 상태를 한번 업데이트하는데 PC 브라우저로 접근해서 나중에 개발자 도구로 모바일 적용을 한다면 isMobile값이 바뀌지 않습니다.. 이런 부분도 같이 고려를 해야할지...?
3. 그리고 저희 언젠가 부터 min-width 막아 놓았던 거가 풀린거 같은데 어느 부분이었더라요...?
---
* P3 : 이런 방법도 …
> [Feat] 접속 기기가 모바일인지 판단하고 그에 따른 제한 처리

- frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.style.ts
- frontend/src/pages/homePage/components/workCardRegister/WorkCardRegister.tsx
- frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.style.ts
- frontend/src/pages/homePage/components/workCardRegisterContent/WorkCardRegisterContent.tsx
- close #466
---
- 작업 카드의 width가 작아 글자가 보이지 않을 경우 hover 시 tooltip이 보이게 구현했습니다
---
https://github.com/user-attachments/assets/de093a27-3a6f-45e2-8e7c-6e71e5cc675a
중앙 정렬
---
---
> [Feat] 작업 일정 width가 작을 경우 hover 시 Tooltip 기능 구현

- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/BatchConfiguration.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/JobScheduler.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/dailyTemperature/processor/DailyTemperatureProcessor.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/daily_high/writer/DailyHighWriter.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/sunRiseSet/writer/SunRiseSetWriter.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/ultraviolet/reader/UVApiCaller.java
- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/ultraviolet/writer/UVWriter.java
- close #442 
---
1. 여러 Batch Job이 같은 Table을 update 할 때 덮어씌여지는 오류를 수정했습니다. 
2. MySQL의 bulk update 쿼리를 사용해서 성능을 향상 시키면서 덮어씌여지는 오류를 수정했습니다. 
상세한 작업 로그는 노션 작업로그에 정리해두었습니다. 
[작업로그](https://foregoing-sofa-1ca.notion.site/Batch-Job-256e13d9782280a68fbcc4f9242223fa?source=copy_link)
---
---
딱히 없습니다. 
---
> [Refactor] Batch writer에서 MySQL Bulk update 적용

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/service/RecommendedWorkService.java
- close #486
---
1. 농작업 추천 목록 개수를 최대 5개로 제한했습니다.
2. myCrop이 없을 경우 예외 처리가 없어서 추가했습니다.
---
없습니다. 
---
> [Fix] 농작업 추천 목록 개수를 최대 5개로 제한

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/weather/service/WeatherService.java
- close #490 
---
1. 기상 그래프 24시간 이내만 반환하도록 수정했습니다. 
---
LocalDate.now를 사용해서 test가 터질 것 같았는데 다행히 안터집니다. 
---
> [Hotifx] 기상 그래프 24시간 이내만 반환하도록 수정

- frontend/src/layouts/navBar/NavBar.styles.ts
- frontend/src/layouts/navBar/NavBar.tsx
- close #494
---
스크롤 감지 훅은 나중에;.. 전역으로 분리할게요
---
---
---
> [Feat] 네브바 로고 라우팅 추가, 스크롤 아래로 내릴 시 네브바 안보이게 구현

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/lifecycle/repository/LifeCycleAndRecommendedWorkRepository.java
- close #209
---
1. 생육단계 Id로 추천 농작업 목록 조회 시 fetch join 사용하도록 해서 N+1 문제를 해결했습니다.
```SQL
[Hibernate] 
select
lcarw1_0.life_cycle_id,
lcarw1_0.recommended_work_id 
from
life_cycle_and_recommended_work lcarw1_0 
join
recommended_work rw1_0 
on lcarw1_0.recommended_work_id=rw1_0.id
[Hibernate] 
select
rw1_0.id,
rw1_0.high_humidity,
rw1_0.high_temperature,
rw1_0.low_humidity,
rw1_0.low_temperature,
rw1_0.name,
rw1_0.rain,
rw1_0.recommendation,
rw1_0.snow,
rw1_0.strong_wind 
from
recommended_work rw1_0 
where
rw1_0.id=?
[Hibernate] 
select
rw1_0.id,
rw1_0.high_humidity,
rw1_0.high_temperature,
rw1_0.low_humidity,
rw1_0.low_temperature,
rw1_0.name,
rw1_0.rain,
rw1_0.recommendation,
rw1_0.snow,
rw1_0.strong_wind 
from
recommended_work rw1_0 
where
rw1_0.id=?
```
```SQL
select …
```
> [Fix] 생육단계 Id로 추천 농작업 목록 조회 시 fetch join 사용

- frontend/src/pages/homePage/components/btnCreateWork/BtnCreateWork.style.ts
- frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.style.ts
- frontend/src/pages/homePage/components/damageInfoCard/DamageInfoCard.tsx
- frontend/src/pages/homePage/components/workContainer/WorkContainer.style.ts
- frontend/src/pages/homePage/components/workContainer/WorkContainer.tsx
- frontend/src/pages/myFarmPage/MyFarmPage.style.ts
- frontend/src/pages/myFarmPage/components/weekNavigator/WeekNavigator.style.ts
- frontend/src/pages/myFarmPage/components/weekNavigator/WeekNavigator.tsx
- frontend/src/pages/myFarmPage/components/weeklyCalendar/WeeklyCalendar.style.ts
- frontend/src/pages/myFarmPage/components/weeklyCalendar/WeeklyCalendar.tsx
- frontend/src/pages/myFarmPage/components/workSchedule/WorkSchedule.tsx
- close #529 
- close #119 
---
- 주간 캘린더 width 수정
- 작물요정님의 작물도 주의가 필요해요 배치 변경
- 내 작물 수가 5개 이상이면 작물 이름이 칸을 벗어나는 현상 flex-wrap으로 처리
- 가로 스크롤 0 일시 오른쪽만 블러, 스크롤 시작 시 양쪽 블러, 스크롤 끝까지 닿았을 때는 왼쪽만 블러
- 추천 작업 카드 hover 시 해당 위치에 고정되어 사이즈 커지게 수정
---
https://github.com/user-attachments/assets/3b2dde03-52fb-4509-ab5b-a499d73b78bf
---
---
> [Feat] 1차 QA 피드백 반영

- backend/src/main/java/com/imsnacks/Nyeoreumnagi/work/util/WorkScheduleCalculator.java
- close #539
---
1. 현재 강수 기준이 0.1 mm 라서 비가 조금이라도 오면 추천 시간대가 확 줄어들었습니다.
- 비가 오더라도 강수량이 적을 때는 추천으로 고려할 수 있도록 강수량 기준을 높였습니다. (`0.1`  -> `2`)
---
없습니다.
---
> [Fix] 추천 농작업에서 강수 기준 mm 를 상향 조정

- batch/src/main/java/com/ImSnacks/NyeoreumnagiBatch/shortTermWeatherForecast/reader/dto/VilageFcstResponseDto.java
nullpointer exception이 getBody 함수에서 발생했습니다. 단기예보 batch에서 응답을 받아오지 못할 시 tomorrow.io를 호춣해야 하는데 응답을 받아오지 못했는지 판단하는 로직 자체에 nullpointer exception이 발생했습니다. 
null 반환 처리를 추가하였습니다. 
---
---
> [Hotfix] 단기예보 batch nullpointerException 오류 해결

- README.md
인프라 구조도에서 S3, CloudFront 위치를 수정했습니다.
---
없습니다.
---
> [Docs] README 작성 (인프라 구조도 수정)

- frontend/src/pages/homePage/desktop/components/workContainer/WorkContainer.tsx
- frontend/src/pages/loginPage/LoginPage.style.ts
- frontend/src/pages/loginPage/LoginPage.tsx
- frontend/src/pages/loginPage/hooks/useLogin.ts
- frontend/src/pages/weatherBoardPage/hooks/useWeatherQuery.ts
- close #565
---
테스트 로그인 버튼을 추가했습니다
테스트 계정 정보는 일단... 하드코딩했는데..
괜찮을지..?
---
---
---
> [Feat] 테스트 로그인 버튼 추가

- README.md
데모 영상에 자막을 추가했습니다.
프론트엔드 디렉토리 구조를 추가했습니다.
---
> [Docs] readme 데모 영상 수정 및 FE 디렉토리 구조 추가
